# Uncomment this line to define a global platform for your project

platform :ios, '7.0'
workspace 'IOSApp'
#配置依赖第三方库的程程
#配置工程中包含POD的target
xcodeproj './IOSApp.xcodeproj'
target 'IOSApp' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for IOSApp
  xcodeproj './IOSApp.xcodeproj'
  pod 'TTKeyBoard', '~> 1.0.0'
  pod 'TTPageView', '~> 0.0.2'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'CocoaAsyncSocket'
end
